version: "3.8"
services:
  mysql:
    image: mysql:5.7.30
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=1000 --default-time_zone='+0:00'
    networks:
      db-net:
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=xiefei
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==ld1"

networks:
  db-net:
    name: db-net
volumes:
  mysql-data:
    name: mysql-data

#  docker stack deploy -c script/docker/ambar-mysql.yml db
