server:
  port: 9002

sync:
  mysql:
    user: sync
    password: yixun2020Sync!
    db: DataCentre
    host: 192.168.0.117
    port: 30542
    driver: com.mysql.cj.jdbc.Driver
  es:
    host: 192.168.0.117
    port: 30573
    mode: http