apiVersion: v1
kind: Pod
metadata:
  name: estest
  labels:
    app: estest
spec:
  containers:
    - name: estest
      image: elasticsearch:7.8.1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9200
      env:
        - name: discovery.type
          value: single-node
  restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: estest
spec:
  selector:
    app: estest
  ports:
    - port: 19200
      targetPort: 9200
  externalIPs:
    - 192.168.1.131
  type: NodePort