apiVersion: v1
kind: PersistentVolume
metadata:
  name: datacentre-mysql-data-pv
spec:
  capacity:
    storage: 50Gi
  nfs:
    path: /nas/data/mysql
    server: ld1
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datacentre-mysql-data-pvc
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteOnce
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datacentre-mysql
spec:
  selector:
    matchLabels:
      app: datacentre-mysql
  serviceName: datacentre-mysql
  replicas: 1
  template:
    metadata:
      name: datacentre-mysql
      labels:
        app: datacentre-mysql
    spec:
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: datacentre-mysql-data-pvc
      containers:
        - name: mysql
          image: imagewarehouse.com/self/yxmysql:0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: xiefei
          args:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_general_ci"
            - "--max_connections=1000"
            - "--default-time_zone=+0:00"
            - "--skip-host-cache"
            - "--skip-name-resolve"
            - "--binlog_format=Row"
            - "--innodb_flush_log_at_trx_commit=1"
            - "--sync_binlog=1"
            - "--max_binlog_size=100M"
            - "--log_output=TABLE"
            - "--slow_query_log=0"
            - "--log_slow_admin_statements=0"
            - "--long_query_time=1"
            - "--log_queries_not_using_indexes=0"
            - "--general_log=0"
            - "--innodb_buffer_pool_instances=16"
            - "--innodb_buffer_pool_size=6G"
            - "--innodb_log_files_in_group=8"
            - "--max_connections=2000"
            - "--max_connect_errors=1000"
            - "--default-storage-engine=innodb"
            - "--key_buffer_size=256M"
            - "--sort_buffer_size=8M"
            - "--join_buffer_size=8M"
            - "--tmp_table_size=64M"



---
apiVersion: v1
kind: Service
metadata:
  name: datacentre-mysql
spec:
  selector:
    app: datacentre-mysql
  ports:
    - port: 3306
  externalIPs:
    - 192.168.1.110

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datacentre-elasticsearch-data-pv
spec:
  capacity:
    storage: 50Gi
  nfs:
    path: /nas/data/elasticsearch
    server: ld1
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datacentre-elasticsearch-data-pvc
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteMany
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datacentre-elasticsearch
spec:
  selector:
    matchLabels:
      app: datacentre-elasticsearch
  serviceName: datacentre-elasticsearch
  replicas: 1
  template:
    metadata:
      name: datacentre-elasticsearch
      labels:
        app: datacentre-elasticsearch
    spec:
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: datacentre-elasticsearch-data-pvc
      containers:
        - name: elasticsearch
          image: elasticsearch:7.8.0
          ports:
            - containerPort: 9200
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
          env:
            - name: discovery.type
              value: single-node


---
apiVersion: v1
kind: Service
metadata:
  name: datacentre-elasticsearch
spec:
  selector:
    app: datacentre-elasticsearch
  ports:
    - port: 9200
  externalIPs:
    - 192.168.1.110

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datacentre-mysql-backup-pv
spec:
  capacity:
    storage: 50Gi
  nfs:
    path: /nas/data/backmysql
    server: ld1
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datacentre-mysql-backup-pvc
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteMany
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: datacentre-mysql-backup
spec:
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: backup-data
              persistentVolumeClaim:
                claimName: datacentre-mysql-backup-pvc
          containers:
            - name: mysql-backup
              image: registry.cn-hangzhou.aliyuncs.com/selfproject/mysql-backup:0.0.4
              volumeMounts:
                - mountPath: /data
                  name: backup-data
              command: ["/bin/bash"]
              args: ["-c","/home/work.sh"]
          restartPolicy: Never


  concurrencyPolicy: Forbid
  schedule: "*/2 * * * *"

