apiVersion: v1
kind: PersistentVolume
metadata:
  name: datacentre-backup-mysql-pv
spec:
  capacity:
    storage: 500Gi
  nfs:
    path: /nas/data/backup/mysql
    server: 192.168.1.131
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datacentre-backup-mysql-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
